spring.application.name=yupiProjet


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/yupiGestionBd}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adrien667}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect